---
title: "DS5110_Project"
author: "Hongyang Wang","Riddhi Rajesh Solanki", "Fangjie Liu"
date: "3/18/2021"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
---

```{r}
library(readr)
VAERSDATA = read_csv("/Users/hongyangwang/OneDrive/2021northeastern/DS 5110 project/DATA/2021VAERSDATA.csv")
VAERSSYMPTOMS = read_csv("/Users/hongyangwang/OneDrive/2021northeastern/DS 5110 project/DATA/2021VAERSSYMPTOMS.csv")
VAERSVAX = read_csv("/Users/hongyangwang/OneDrive/2021northeastern/DS 5110 project/DATA/2021VAERSVAX.csv")
vaccinations = read_csv("/Users/hongyangwang/OneDrive/2021northeastern/DS 5110 project/DATA/us_state_vaccinations.csv")

str(VAERSDATA)
str(VAERSSYMPTOMS)
str(VAERSVAX)
str(vaccinations)

```

```{r}
library(dplyr)
countNA <- function(data){
   x <- data%>%select(everything()) %>% summarise_all(funs(sum(is.na(.))))
   x
}
```

```{r}
# look the raw data and check the missing values.
head(VAERSDATA)
countNA(VAERSDATA)
str(VAERSDATA)

head(VAERSSYMPTOMS)
countNA(VAERSSYMPTOMS)

head(VAERSVAX)
countNA(VAERSVAX)

head(vaccinations)
countNA(vaccinations)
str(vaccinations)
```
```{r}





```
