---
title: "Project 5110"
author: "Riddhi Solanki"
date: "4/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("janitor")
library(janitor)
library(tidyverse)
library(dplyr)
library(readr)
```

#importing data
```{r}
patient_data<-read.csv("C:/Users/solan/Downloads/2021VAERSDATA.csv/2021VAERSDATA.csv",na.strings=c("","NA"))
vax_data<-read.csv("C:/Users/solan/Downloads/2021VAERSVAX.csv/2021VAERSVAX.csv",na.strings=c("","NA"))
symptoms_data<-read.csv("C:/Users/solan/Downloads/2021VAERSSYMPTOMS.csv/2021VAERSSYMPTOMS.csv")

```


```{r}
head(patient_data)
head(vax_data)
head(symptoms_data)
```

##Vaccination Data 

#seeing what type of vaccines are in the dataset

```{r}
vax_data %>% group_by(VAX_TYPE)%>% summarize(count=n())
```

#we need only COVID for the purpose of this analysis
```{r}
vax_data<-vax_data %>% filter(VAX_TYPE=="COVID19")
vax_data
```

#dropping na
```{r}
vax_tidy<-vax_data[,-4]
colSums(is.na(vax_tidy))
vax_tidy<- vax_tidy%>% drop_na()
#vax_tidy
```

##Symptom data:

```{r}
head(symptoms_data)
```



```{r}
symptoms_tidy<- symptoms_data[,c(-3,-5,-7,-9,-11)]
symptoms_tidy<- symptoms_tidy%>% pivot_longer(cols = 'SYMPTOM1':'SYMPTOM5', names_to = "symp_number", values_to = "Symptom", values_drop_na =TRUE)

symptoms_tidy<-symptoms_tidy[!(symptoms_tidy$Symptom==""),]

symptoms_tidy$symp_number<-as.integer(gsub('[a-zA-Z]', '',symptoms_tidy$symp_number))

symptom_occurence<-symptoms_tidy
symptom_list<-unique(symptom_occurence$Symptom)
symptom_list

symptoms_tidy<-symptoms_tidy%>%
  group_by(VAERS_ID)%>%
  mutate(count=n())

symptoms_tidy<-symptoms_tidy%>%group_by(VAERS_ID)%>%
  summarise(Symptoms = toString(unique(Symptom)))

symptom_occurence%>%group_by(Symptom)%>%summarise(count=n())%>%arrange(-count)%>% top_n(20)

```

```{r}
symptomsOfInterest <- c("Appendicitis","Anaphylactic reaction","Diarrhoea","Chills",
                        "Dizziness","Nausea","Vomiting","Pain","Headache","Pyrexia",
                        "Fatigue", "Death", "Tinnitus", "Urticaria", "Injection site pain", 
                        "Injection site warmth", "Injection site pruritus", 
                        "Injection site erythema", "Injection site swelling", 
                        "Lymphadenopathy", "Arthralgia", "Thrombosis", 
                        "Abortion spontaneous", "Dyspnoea", "COVID-19","Asthenia",
                        "Malaise","Cough","Hypoaesthesia","Rash","Feeling abnormal",
                        "Chest pain","Loss of consciousness","Facial paralysis","Flushing",
                        "Muscular weakness","Throat tightness","Hyperhidrosis",
                        "Tremor")


symptomsOfInterest <- sort(symptomsOfInterest)

for (sympt in symptomsOfInterest) {
    sympt_col_name <- make.names(sympt) #converts the symptom string into a valid column name
    symptoms_tidy[[sympt_col_name]] <- grepl(sympt, symptoms_tidy$Symptoms, ignore.case=TRUE) 
}
head(symptoms_tidy)
 
```

##Patient data
```{r}

head(patient_data) 
```

#35 columns

#Remove columns with more thean 50% missing values

```{r}
patient_tidy<-
  patient_data%>%remove_empty(which = c("rows", "cols"))%>%
  purrr::discard(~sum(is.na(.x))/length(.x)* 100 >=50)
```

#18 columns


#Out of these removing columns not needed for this analysis
```{r}
patient_tidy<-patient_tidy[,c("VAERS_ID", "STATE","AGE_YRS","SEX","RECOVD","VAX_DATE","NUMDAYS","V_ADMINBY")]

colSums(is.na(patient_tidy))
```

```{r}
#dropping missing values
patient_tidy<- patient_tidy%>% drop_na()

```


#Joining data

```{r}


join1<-left_join(patient_tidy,symptoms_tidy,by='VAERS_ID')

vaers_dataset<-left_join(join1,vax_tidy,by="VAERS_ID")
colSums(is.na(vaers_dataset))
vaers_dataset<-vaers_dataset%>%drop_na()
vaers_dataset



```













